PS E:\DjangoStuff> pip freeze    /*Sto e instalirano 
virtualenv==16.6.1
PS E:\DjangoStuff> ls


    Directory: E:\DjangoStuff


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        08-Jul-19     12:10                Include
d-----        08-Jul-19     12:40                Lib
d-----        09-Jul-19     13:32                my_app
d-----        08-Jul-19     12:53                Scripts                 //// tuka vo skripts e Virtual inv
d-----        08-Jul-19     12:40                tcl
-a----        25-Mar-19     20:31          30195 LICENSE.txt


PS E:\DjangoStuff> ./Scripts/activate                   //// tuka se aktivira VInvaerment...
(DjangoStuff) PS E:\DjangoStuff>


(DjangoStuff) PS E:\DjangoStuff> pip freeze
Django==2.2.3
pytz==2019.1
sqlparse==0.3.0
(DjangoStuff) PS E:\DjangoStuff> pip install django
Requirement already satisfied: django in e:\djangostuff\lib\site-packages (2.2.3)
Requirement already satisfied: sqlparse in e:\djangostuff\lib\site-packages (from django) (0.3.0)
Requirement already satisfied: pytz in e:\djangostuff\lib\site-packages (from django) (2019.1)
(DjangoStuff) PS E:\DjangoStuff> cd my_app
(DjangoStuff) PS E:\DjangoStuff\my_app> django-admin.py startproject todo_app .
CommandError: E:\DjangoStuff\my_app\manage.py already exists, overlaying a project or app into an existing directory won't replace conflicting files
(DjangoStuff) PS E:\DjangoStuff\my_app> ls


    Directory: E:\DjangoStuff\my_app


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        09-Jul-19     13:10                todo_app
d-----        09-Jul-19     14:47                todo_list
-a----        09-Jul-19     13:27         131072 db.sqlite3
-a----        08-Jul-19     12:59            649 manage.py


(DjangoStuff) PS E:\DjangoStuff\my_app> ls


    Directory: E:\DjangoStuff\my_app


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        09-Jul-19     13:10                todo_app
d-----        09-Jul-19     14:47                todo_list
-a----        09-Jul-19     13:27         131072 db.sqlite3
-a----        08-Jul-19     12:59            649 manage.py


(DjangoStuff) PS E:\DjangoStuff\my_app> python manage.ppy runserver                       ///////////////////tuka se startuva serverot 
E:\DjangoStuff/Scripts\python.exe: can't open file 'manage.ppy': [Errno 2] No such file or directory
(DjangoStuff) PS E:\DjangoStuff\my_app> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
July 15, 2019 - 20:43:06
Django version 2.2.3, using settings 'todo_app.settings'
Starting development server at http://127.0.0.1:8000/                    ////////////////tuka pocnuva serverot so rabota 
Quit the server with CTRL-BREAK.
[15/Jul/2019 20:43:46] "GET / HTTP/1.1" 200 20
Not Found: /favicon.ico
[15/Jul/2019 20:43:46] "GET /favicon.ico HTTP/1.1" 404 2134



+++++++++++++++++++++++++++++++++++++++++++++
posle ovoa otvarame nov windows power shell


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ovoa e od novio prozor na WPShell :
zatoa so na drugio rabote servero 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> cd E:\DjangoStuff
PS E:\DjangoStuff> cd my_app
PS E:\DjangoStuff\my_app> python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 16, in main
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
PS E:\DjangoStuff\my_app> cd E:\DjangoStuff
PS E:\DjangoStuff> ls


    Directory: E:\DjangoStuff


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        08-Jul-19     12:10                Include
d-----        08-Jul-19     12:40                Lib
d-----        09-Jul-19     13:32                my_app
d-----        08-Jul-19     12:53                Scripts
d-----        08-Jul-19     12:40                tcl
-a----        15-Jul-19     20:47           3498 Kako se pravi to do listata po red.txt
-a----        25-Mar-19     20:31          30195 LICENSE.txt


PS E:\DjangoStuff> ./Scripts/activate             //////////////Se aktivira Virtual envoirment
(DjangoStuff) PS E:\DjangoStuff> cd my_app
(DjangoStuff) PS E:\DjangoStuff\my_app> python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
(DjangoStuff) PS E:\DjangoStuff\my_app> python manage.py startapp todo_list   ////////se aktivira todo listata   
CommandError: 'todo_list' conflicts with the name of an existing Python module and cannot be used as an app name. Please try another name.
(DjangoStuff) PS E:\DjangoStuff\my_app>


